#!/usr/bin/env python3
"""Generate a compact, grep-able symbol map of the repo for agent navigation.

The map turns "where is symbol X?" into a single ripgrep call that returns an
exact ``path:line`` jump target, so an agent reads the one relevant slice of a
file instead of the whole 800-1200-line module. Token-efficiency tooling, not
part of the pipeline.

Usage::

    python scripts/repomap.py            # regenerate .claude/repomap.md
    python scripts/repomap.py --check    # exit 1 if the committed map is stale

Find a symbol::   rg '\\bNAME\\b' .claude/repomap.md   -> path:line -> Read(path, offset=line)
One file::        rg 'relpath/file.py' .claude/repomap.md

Python symbols come from the stdlib ``ast`` (exact); R symbols come from a
regex over ``name <- function(...)`` definitions (good enough to navigate).
The committed map is guarded by ``tests/test_repomap.py`` so it cannot rot.
"""

from __future__ import annotations

import argparse
import ast
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / ".claude" / "repomap.md"

# renv/activate.R is vendored bootstrap, not project code.
EXCLUDE_PREFIXES = ("renv/",)
MAX_SIG = 140

HEADER = (
    "# Repo symbol map — autogenerated by scripts/repomap.py (drift-guarded by tests/test_repomap.py).\n"
    "# Regenerate after editing code:  python scripts/repomap.py\n"
    "#\n"
    "# Jump to a symbol:  rg '\\bNAME\\b' .claude/repomap.md  ->  path:line  ->  Read(path, offset=line)\n"
    "# List one file:     rg 'relpath/file.py' .claude/repomap.md\n"
    "# Lines are  path:line: <signature>  so a single rg hit is a ready jump target.\n"
)

R_FUNC = re.compile(r"^\s*([A-Za-z.][\w.]*)\s*(?:<-|=)\s*function\s*\((.*)$")


def _tracked() -> list[str]:
    """Tracked .py/.R paths, sorted, minus vendored trees."""
    res = subprocess.run(
        ["git", "ls-files", "*.py", "*.R"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    files = [
        line for line in res.stdout.splitlines() if line and not line.startswith(EXCLUDE_PREFIXES)
    ]
    return sorted(files)


def _truncate(text: str) -> str:
    text = " ".join(text.split())  # collapse multi-line signatures onto one line
    return text if len(text) <= MAX_SIG else text[: MAX_SIG - 1] + "…"


def _func(node: ast.FunctionDef | ast.AsyncFunctionDef, qual: str) -> str:
    kw = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
    ret = f" -> {ast.unparse(node.returns)}" if node.returns else ""
    return _truncate(f"{kw} {qual}({ast.unparse(node.args)}){ret}")


def _valtype(value: ast.expr | None) -> str:
    if value is None:
        return "..."
    if isinstance(value, ast.Dict):
        return f"dict[{len(value.keys)}]"
    if isinstance(value, ast.List):
        return f"list[{len(value.elts)}]"
    if isinstance(value, ast.Tuple):
        return f"tuple[{len(value.elts)}]"
    if isinstance(value, ast.Set):
        return f"set[{len(value.elts)}]"
    if isinstance(value, ast.Call):
        return _truncate(f"{ast.unparse(value.func)}(...)")
    if isinstance(value, ast.Constant):
        return type(value.value).__name__
    return value.__class__.__name__.lower()


def _is_notable_name(name: str) -> bool:
    # Module-level constants/registries/schemas, plus the public-API __all__.
    return name == "__all__" or (name.isupper() and len(name) > 1)


def _py_symbols(src: str) -> list[tuple[int, str]]:
    try:
        tree = ast.parse(src)
    except SyntaxError as exc:  # pragma: no cover - defensive
        return [(getattr(exc, "lineno", 1) or 1, f"# UNPARSABLE: {exc.msg}")]
    out: list[tuple[int, str]] = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            out.append((node.lineno, _func(node, node.name)))
        elif isinstance(node, ast.ClassDef):
            bases = ", ".join(ast.unparse(b) for b in node.bases)
            out.append(
                (node.lineno, _truncate(f"class {node.name}" + (f"({bases})" if bases else "")))
            )
            out.extend(
                (sub.lineno, _func(sub, f"{node.name}.{sub.name}"))
                for sub in node.body
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef))
            )
        elif isinstance(node, ast.Assign):
            out.extend(
                (node.lineno, f"{tgt.id} = {_valtype(node.value)}")
                for tgt in node.targets
                if isinstance(tgt, ast.Name) and _is_notable_name(tgt.id)
            )
        elif (
            isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and _is_notable_name(node.target.id)
        ):
            out.append((node.lineno, f"{node.target.id} = {_valtype(node.value)}"))
    out.sort(key=lambda item: item[0])
    return out


def _r_symbols(src: str) -> list[tuple[int, str]]:
    out: list[tuple[int, str]] = []
    for lineno, line in enumerate(src.splitlines(), start=1):
        match = R_FUNC.match(line)
        if match:
            name, rest = match.group(1), match.group(2)
            args = rest.split(")")[0].rstrip(", ")  # R sigs may span lines
            if ")" not in rest and args:
                args += ", …"  # signature continues on the next line
            out.append((lineno, _truncate(f"{name} <- function({args})")))
    return out


def build() -> str:
    blocks: list[str] = [HEADER]
    for rel in _tracked():
        src = (ROOT / rel).read_text(encoding="utf-8", errors="replace")
        nlines = src.count("\n") + 1
        symbols = _py_symbols(src) if rel.endswith(".py") else _r_symbols(src)
        if not symbols:
            continue
        lines = [f"\n# {rel} ({nlines} lines)"]
        lines += [f"{rel}:{lineno}: {text}" for lineno, text in symbols]
        blocks.append("\n".join(lines))
    return "\n".join(blocks) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed map differs from freshly generated output",
    )
    args = parser.parse_args(argv)
    content = build()
    if args.check:
        current = MAP.read_text(encoding="utf-8") if MAP.exists() else ""
        if current != content:
            print(
                "repomap.md is stale — regenerate with: python scripts/repomap.py",
                file=sys.stderr,
            )
            return 1
        return 0
    MAP.write_text(content, encoding="utf-8")
    print(f"wrote {MAP.relative_to(ROOT)} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
